name: GHCR Cleanup

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 0'  # every Sunday at 03:00 UTC

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Extract and lowercase repo name
        run: |
          REPO_FULL=${GITHUB_REPOSITORY}               # e.g. "LedoKun/028-simple-queue-system"
          REPO_NAME=${REPO_FULL#*/}                    # strips the owner, yields "028-simple-queue-system"
          echo "REPO_NAME_LC=${REPO_NAME,,}" >> $GITHUB_ENV

      - name: Cleanup old images
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          package: ${{ env.REPO_NAME_LC }}             # now just "028-simple-queue-system"
          keep-n-tagged: 2
          keep-n-untagged: 2
