name: GHCR Cleanup

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 0'  # Runs every Sunday at 03:00 UTC

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Set lowercase repository name
        run: echo "REPO_LC=${REPO,,}" >> $GITHUB_ENV
        env:
          REPO: ${{ github.repository }}

      - name: Cleanup old images
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          keep-n-tagged: 2
          keep-n-untagged: 2
          package: ${{ env.REPO_LC }}
          owner: ${{ github.repository_owner }}
